# Generated by Django 3.2.3 on 2021-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='time_played',
            field=models.FloatField(default=0),
        ),
    ]
