# Generated by Django 3.2.3 on 2021-07-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_viewedlessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedlessons',
            name='curs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
