# Generated by Django 3.2.3 on 2021-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_viewedlessons_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=models.BinaryField(null=True),
        ),
    ]
